import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowUpRight, PartyPopper } from 'lucide-react'
import { SectionHeading } from '../components/SectionHeading'

export function Reservation() {
  const [submitted, setSubmitted] = useState(false)
  const [date, setDate] = useState('')
  const today = new Date().toISOString().split('T')[0]
  return <section className="reservation-section section-pad" id="reserve"><div className="reservation-intro"><SectionHeading eyebrow="We’ll save you a seat" title={<>Stay for<br /><em>another cup.</em></>} copy="For brunch, a catch-up, or just a little more time together." /><div className="reservation-note"><span>WALK-INS ARE ALWAYS WELCOME</span><p>For parties of 7 or more, give us a call and we’ll find a way to make it work.</p><a className="inline-link" href="tel:+15035550186">(503) 555-0186 <ArrowUpRight size={15} /></a></div></div><div className="reservation-form-wrap"><AnimatePresence mode="wait">{submitted ? <motion.div key="success" className="reservation-success" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}><span><PartyPopper size={25} /></span><h3>Your table is on our mind.</h3><p>Thanks for reaching out. We’ve noted your request and look forward to seeing you.</p><button className="inline-link" onClick={() => setSubmitted(false)}>Make another reservation <ArrowUpRight size={15} /></button></motion.div> : <motion.form key="form" className="reservation-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }} initial={{ opacity: 0 }} animate={{ opacity: 1 }}><div className="form-title"><h3>Book a little time</h3><span>Usually confirmed within an hour</span></div><label>Your name<input name="name" placeholder="Name on the reservation" required minLength={2} autoComplete="name" /></label><div className="form-row"><label>Date<input name="date" type="date" min={today} required value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Time<select name="time" required defaultValue=""><option value="" disabled>Select a time</option>{['8:00 am', '9:00 am', '10:00 am', '11:00 am', '12:00 pm', '1:00 pm', '2:00 pm'].map((time) => <option key={time}>{time}</option>)}</select></label></div><label>Number of guests<select name="guests" defaultValue="2">{[1, 2, 3, 4, 5, 6].map((count) => <option key={count} value={count}>{count} {count === 1 ? 'guest' : 'guests'}</option>)}</select></label><button className="button button--dark form-submit" type="submit">Request a table <ArrowUpRight size={16} /></button><p className="form-privacy">We’ll only use your details to hold your table.</p></motion.form>}</AnimatePresence></div></section>
}